"""Generate native Windows layout tables and offline preview data."""
import json
import unicodedata
from pathlib import Path
import argparse
import shutil
import subprocess
import zipfile
from dictionary_import import generate as generate_dictionary

ROOT = Path(__file__).resolve().parent
ID = 'kbdroh'

def mappings():
    base = dict(zip('ABP,TJ;HQF.DR/ZSCKGLMNW[Y]X\'', map(chr, range(0x10D00, 0x10D1C))))
    base.update(zip('VIUEO', map(chr, range(0x10D1D, 0x10D22))))
    base.update({str(i): chr(0x10D30+i) for i in range(10)})
    base.update({'`': chr(0x10D22), '\\': chr(0x10D23), '-':'-', '=':'=', ' ':' '})
    # SIL explicitly suppresses unused shifted letters. None means no output.
    shifted = {k: None for k in base if k.isalpha()}
    shifted.update(dict(zip('HTA`', map(chr, range(0x10D24, 0x10D28)))))
    shifted.update({'L':'؛', ',':'،', '.':'۔', '/':'؟', ' ':chr(0x10D22)})
    shifted.update(dict(zip('1234567890-=[]\\;\'', '!@#$%^&*()_+{}|:"')))
    return {'base':base, 'shift':shifted}

VK = {'`':0xC0,'-':0xBD,'=':0xBB,'[':0xDB,']':0xDD,'\\':0xDC,';':0xBA,"'":0xDE,',':0xBC,'.':0xBE,'/':0xBF,' ':0x20}
def vkey(key):
    return VK.get(key, ord(key))

def native_entries():
    data = mappings()
    entries = []
    for key in data['base']:
        ctrl = ord(key)-64 if key.isalpha() else {'[':27,']':29,'\\':28,' ':32}.get(key)
        shift_ctrl = {'2':0,'6':30,'-':31}.get(key,ctrl)
        entries.append((vkey(key),[ord(data['base'][key]),ord(data['shift'][key]) if data['shift'][key] is not None else None,ctrl,shift_ctrl]))
    # Numpad emits ASCII for numeric entry. ISO extra key retains backslash.
    entries.extend((0x60+i,[48+i,48+i,None,None]) for i in range(10))
    entries.extend([(8,[8,8,127,127]),(9,[9,9,None,None]),(13,[13,13,10,10]),
                    (27,[27]*4),(3,[3]*4),(0xE2,[92,124,28,28])])
    entries.extend((vk,[cp,cp,None,None]) for vk,cp in [(0x6A,42),(0x6B,43),(0x6D,45),(0x6E,46),(0x6F,47)])
    return sorted(entries)

def utf16(cp):
    raw = chr(cp).encode('utf-16-le')
    return [int.from_bytes(raw[i:i+2],'little') for i in range(0,len(raw),2)]

def generate():
    generate_dictionary(ROOT)
    (ROOT/'native').mkdir(exist_ok=True)
    chars, ligatures = [], []
    for vk, values in native_entries():
        row=[]
        for state, cp in enumerate(values):
            if cp is None:
                row.append('WCH_NONE')
            elif cp > 0xFFFF:
                row.append('WCH_LGTR')
                hi,lo = utf16(cp)
                ligatures.append(f'  {{0x{vk:02X},{state},{{0x{hi:04X},0x{lo:04X}}}}},')
            else:
                row.append(f'0x{cp:04X}')
        chars.append(f'  {{0x{vk:02X},0,{{{",".join(row)}}}}},')
    text = '/* Generated by build.py. Do not edit. */\nstatic VK_TO_WCHARS4 characters[] = {\n'+'\n'.join(chars)+'\n  {0,0,{0,0,0,0}}\n};\n'
    text += 'static LIGATURE2 ligatures[] = {\n'+'\n'.join(ligatures)+'\n  {0,0,{0,0}}\n};\n'
    (ROOT/'native/layout.inc').write_text(text)
    ime_keys = {vk: values[:2] for vk, values in native_entries() if vk >= 0x20 and vk != 0xE2}
    (ROOT/'ime/keys.inc').write_text('// Generated by build.py.\nstatic const unsigned keyMap[256][2] = {\n' + '\n'.join('  {%d,%d},' % tuple(v or 0 for v in ime_keys.get(vk, [0, 0])) for vk in range(256)) + '\n};\n')
    data=mappings()
    names = {v:unicodedata.name(v,'SPACE') for keys in data.values() for v in keys.values() if v is not None}
    (ROOT/'layout.js').write_text('const ROHINGYA = '+json.dumps({'layers':data,'names':names},ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
    # Windows acceptance test consumes generated Unicode scalar expectations.
    (ROOT/'windows/expected-layout.json').write_text(json.dumps(native_entries(),indent=2)+'\n')

def compile_package(zig):
    out=ROOT/'dist/Hanifi-Rohingya-Windows-x64'
    out.mkdir(parents=True,exist_ok=True)
    subprocess.run([zig,'build-lib','-target','x86_64-windows-msvc','-dynamic','-fentry=DllMainCRTStartup',
                    '-O','ReleaseSmall','-femit-bin='+str(out/'kbdroh.dll'),
                    '-cflags','-std=c11','-Wall','-Wextra','-Werror','--',str(ROOT/'native/keyboard.c')],check=True)
    subprocess.run([zig, 'c++', '-target', 'x86_64-windows-gnu', '-std=c++17', '-O2',
                    '-shared', '-static', '-Wall', '-Wextra', '-Werror', '-o', str(out/'rohime.dll'),
                    str(ROOT/'ime/service.cpp'), str(ROOT/'ime/exports.def'), '-lole32', '-loleaut32', '-luuid', '-luser32', '-lgdi32', '-ladvapi32'], check=True)
    for name in ('install.ps1','uninstall.ps1','enable.ps1','test-windows.ps1','expected-layout.json','Install.cmd','Uninstall.cmd','install-predictive.ps1','Install-Predictive.cmd','Uninstall-Predictive.cmd'):
        shutil.copy2(ROOT/'windows'/name,out/name)
    shutil.copy2(ROOT/'assets/NotoSansHanifiRohingya-Regular.ttf',out)
    shutil.copy2(ROOT/'assets/OFL.txt',out)
    shutil.copy2(ROOT/'keyboard/LICENSE.md',out/'LAYOUT-LICENSE.txt')
    shutil.copy2(ROOT/'README.md',out/'README.md')
    for name in ('preview.html', 'preview.js', 'layout.js', 'prediction.js', 'preview-prediction.js'):
        shutil.copy2(ROOT/name, out/name)
    shutil.copytree(ROOT/'assets', out/'assets', dirs_exist_ok=True)
    shutil.copytree(ROOT/'dictionary', out/'dictionary', dirs_exist_ok=True)
    archive=ROOT/'dist/Hanifi-Rohingya-Windows-x64.zip'
    with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED) as z:
        for path in sorted(out.rglob('*')):
            if path.is_file(): z.write(path,f'{out.name}/{path.relative_to(out).as_posix()}')
    print(f'Built {archive}')

if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--compile',action='store_true',help='Compile the x64 Windows DLL and package it')
    parser.add_argument('--zig',default='zig',help='Path to Zig 0.14.1 executable')
    args=parser.parse_args()
    generate()
    if args.compile:
        compile_package(args.zig)
